GET http://localhost:3000

###

POST http://localhost:3000/api/v1/users
content-type: application/json

{
  "citizen_id": "1005037454", 
  "name": "Kevin Sneyder Hernandez Camacho",
  "email": "45645@gmail.com",
  "phone_number": "3133321318",
  "password": "kevinxdlolsigma",
  "role_id": "1"
}

###

GET http://localhost:3000/api/v1/users?limit=10&offset=0&expand=role_id

###

GET http://localhost:3000/api/v1/users?limit=10&offset=0

###

GET http://localhost:3000/api/v1/users

###

GET http://localhost:3000/api/v1/users/1

###

GET http://localhost:3000/api/v1/users/1?expand=role_id

###

DELETE http://localhost:3000/api/v1/users/1

###

PUT http://localhost:3000/api/v1/users/2
content-type: application/json

{
  "role_id": "2"
}

###

# eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InBydWViYUBjb3JyZW8uY29tIiwiaWF0IjoxNzE4NzcwNjUyLCJleHAiOjE3MTg3NzQyNTJ9.1ccY-Fv8UCHKCR2Ujv8aNFBsAWp0FEZiNP7tDE88Myw